export const items = [
  {
    id: 1,
    title: "breakfast",
    description: "breakfastbreakfastbreakfastbreakfast",
    price: 50,
    category: "Breakfast",
    img: "1.jpg",
  },
  {
    id: 2,
    title: "Lunch",
    description: "LunchLunchLunchLunchLunch",
    price: 50,
    category: "Lunch",
    img: "3.jpg",
  },
  {
    id: 3,
    title: "breakfast",
    description: "breakfastbreakfastbreakfastbreakfast",
    price: 50,
    category: "Breakfast",
    img: "2.jpg",
  },
  {
    id: 4,
    title: "Lunch",
    description: "LunchLunchLunchLunchLunchLunch",
    price: 50,
    category: "Lunch",
    img: "3.jpg",
  },
  {
    id: 5,
    title: "Dinner",
    description: "DinnerDinnerDinnerDinnerDinnerDinner",
    price: 50,
    category: "Dinner",
    img: "2.jpg",
  },
  {
    id: 6,
    title: "snack",
    description: "snacksnacksnacksnack",
    price: 50,
    category: "snack",
    img: "2.jpg",
  },
];
